import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HeroSection from "@/components/home/HeroSection";
import AboutSection from "@/components/home/AboutSection";
import ClientSection from "@/components/home/ClientSectionl";
import Expertise from "@/components/home/Experties";
import OurWork from "@/components/home/OurWork";
import HappyCustomer from "@/components/home/HappyCustomer";
import FutureCTA from "@/components/home/FutureCTA";
import OurJourney from "@/components/home/OurJourney";
import StatsSection from "@/components/home/StateSection";
import MessageSection from "@/components/home/MessageSection";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home_page}>
        <section className={styles.hero_section}>
          <HeroSection/>
        </section>
        <section className={styles.about_section}>
          <AboutSection/>
        </section>
        <section className={styles.client_section}>
          <ClientSection/>
        </section>
        <section className={styles.journey_section}>
          <OurJourney/>
        </section>
        <section className={styles.message_section}>
          <MessageSection/>
        </section>
        <section className={styles.expertise_section}>
          <Expertise/>
        </section>
        <section className={styles.work_section}>
          <OurWork/>
        </section>
        <section className={styles.state_section}>
          <StatsSection/>
        </section>
        <section className={styles.customer_section}>
          <HappyCustomer/>
        </section>
        <section className={styles.cta_section}>
          <FutureCTA/>
        </section>
      </main>
    </>
  );
}
