import Head from "next/head";
import { useEffect } from "react";
import styles from "@/styles/Home.module.css";
import CtaSection from "@/components/home/CtaSection";
import HeroSection from "@/components/home/HeroSection";
import AboutSection from "@/components/home/AboutSection";
import PartnerSection from "@/components/home/ParterSection";
import ProcessSection from "@/components/home/ProcessSection";
import ProjectSection from "@/components/home/ProjectSection";
import ServicesSection from "@/components/home/ServicessSection";
import ServicesMobile from "@/components/home/ServicesMobile";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export default function Home() {
  useEffect(() => {
    if ("scrollRestoration" in history) {
      history.scrollRestoration = "manual";
    }

    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home_page}>
        <section id="home" className={styles.hero_section}>
          <HeroSection />
        </section>
        <section id="about" className={styles.about_section}>
          <AboutSection />
        </section>
        <section id="services" className={styles.services_section}>
          <div className={styles.desktop}>
            <ServicesSection />
          </div>
          <div className={styles.mobile}>
            <ServicesMobile />
          </div>
        </section>
        <section id="projects" className={styles.project_section}>
          <ProjectSection />
        </section>
        <section className={styles.process_section}>
          <ProcessSection />
        </section>
        <section className={styles.partner_section}>
          <PartnerSection />
        </section>
        <section className={styles.cta_section}>
          <CtaSection />
        </section>
      </main>
    </>
  );
}
