import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HeroSection from "@/components/home/HeroSection";
import AboutSection from "@/components/home/AboutSection";
import ClientCarousel from "@/components/home/ClientCarousel";
import RunningTestimonials from "@/components/home/RunningTestimonials";
import Expertise from "@/components/home/Experties";
import OurWork from "@/components/home/OurWork";
import HappyCustomer from "@/components/home/HappyCustomer";
import FutureCTA from "@/components/home/FutureCTA";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home_page}>
        <section className={styles.section}>
          <HeroSection/>
          <AboutSection/>
          <ClientCarousel/>
          <RunningTestimonials/>
          <Expertise/>
          <OurWork/>
          <HappyCustomer/>
          <FutureCTA/>
        </section>
      </main>
    </>
  );
}
